# Generated by Django 2.2.7 on 2019-11-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('SUMMER', 'Summer'), ('SPRING', 'Spring'), ('WINTER', 'Winter'), ('UNKNOWN', 'Unknown'), ('FALL', 'Fall')], default='UNKNOWN', max_length=6)),
                ('year', models.CharField(choices=[('SUMMER', 'Summer'), ('SPRING', 'Spring'), ('WINTER', 'Winter'), ('UNKNOWN', 'Unknown'), ('FALL', 'Fall')], default='0000', max_length=4)),
            ],
        ),
    ]
