# Generated by Django 2.2.7 on 2019-11-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_auto_20191114_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(choices=[('FALL', 'Fall'), ('WINTER', 'Winter'), ('UNKNOWN', 'Unknown'), ('SPRING', 'Spring'), ('SUMMER', 'Summer')], default='UNKNOWN', max_length=6),
        ),
    ]
