# Generated by Django 2.2.7 on 2019-11-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_auto_20191115_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('WINTER', 'Winter'), ('SPRING', 'Spring'), ('FALL', 'Fall'), ('SUMMER', 'Summer')], default='UNKNOWN', max_length=6),
        ),
    ]
