# Generated by Django 2.2.7 on 2019-11-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_auto_20191115_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(choices=[('SUMMER', 'Summer'), ('WINTER', 'Winter'), ('FALL', 'Fall'), ('SPRING', 'Spring'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=6),
        ),
    ]
