# Generated by Django 2.2.7 on 2019-11-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_auto_20191116_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('FALL', 'Fall'), ('WINTER', 'Winter')], default='UNKNOWN', max_length=6),
        ),
    ]
