# Generated by Django 2.2.7 on 2019-11-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_auto_20191116_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(choices=[('WINTER', 'Winter'), ('FALL', 'Fall'), ('SUMMER', 'Summer'), ('SPRING', 'Spring'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=6),
        ),
    ]
