# Generated by Django 2.2.7 on 2019-11-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0013_auto_20191117_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('FALL', 'Fall'), ('WINTER', 'Winter'), ('SPRING', 'Spring'), ('SUMMER', 'Summer')], default='UNKNOWN', max_length=6),
        ),
    ]
