# Generated by Django 2.2.7 on 2019-11-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0015_auto_20191117_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(choices=[('WINTER', 'Winter'), ('SPRING', 'Spring'), ('UNKNOWN', 'Unknown'), ('FALL', 'Fall'), ('SUMMER', 'Summer')], default='UNKNOWN', max_length=6),
        ),
    ]
