# Generated by Django 2.2.7 on 2019-11-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0016_auto_20191117_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(choices=[('SPRING', 'Spring'), ('WINTER', 'Winter'), ('UNKNOWN', 'Unknown'), ('SUMMER', 'Summer'), ('FALL', 'Fall')], default='UNKNOWN', max_length=6),
        ),
    ]
